In [1]:
%load_ext autoreload
%autoreload 2

In [23]:
from quantum_DP import *

## Locally Greedy

In [29]:
N, g, q, Qp = 7, 0.3, 1/2, 100
identical, use_CUDA = False, True
device, cache = 'cuda:0' if use_CUDA else 'cpu', not use_CUDA
rho_pos, rho_neg = generate_rhos(N, identical, g, dim=2, is_complex=False)

kwargs = {
    'N': N, 'rho_pos': rho_pos, 'rho_neg': rho_neg, 'interp_mode': 'linear',
    'Qp': Qp, 'device': device, 'cache': cache
}

prob_succ_H = helstrom(q, rho_pos, rho_neg)

Asp = Locally_Greedy_ParamSpace(N, rho_pos, rho_neg, Qp, device)
LG_QDP = Quantum_DP(**kwargs, param_space=Asp)
prob_succ_LG = LG_QDP.root.prob_success(q)

if not identical:
    print('System with {0} different qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Locally greedy:\n    Best order  {0:.6f}\n    Worst order {1:.6f}'.format(
        *prob_succ_LG))
else:
    print('System with {0} identical qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Locally greedy   {0:.6f}'.format(*prob_succ_LG))

simulate(LG_QDP, 1000, q);

System with 7 different qubits
Depolarizing parameter g = 0.3
Helstrom:
    Global 0.923635
    Local 0.903486
Locally greedy:
    Best order  0.911634
    Worst order 0.832659


probability of success is 0.907


## Qubit Projective vs Qubit Extremal POVM

In [52]:
N, g, q, Qp = 3, 0.3, 1/2, 100
identical, use_CUDA = False, True
device, cache = 'cuda:0' if use_CUDA else 'cpu', not use_CUDA
rho_pos, rho_neg = generate_rhos(N, identical, g, dim=2, is_complex=False)

kwargs = {
    'N': N, 'rho_pos': rho_pos, 'rho_neg': rho_neg, 'interp_mode': 'linear',
    'Qp': Qp, 'device': device, 'cache': cache
}

prob_succ_H = helstrom(q, rho_pos, rho_neg)

Asp = Qubit_Proj_ParamSpace(Qphi=16, device=device)
Qb_QDP = Quantum_DP(**kwargs, param_space=Asp)
prob_succ_B = Qb_QDP.root.prob_success(q)

Asp_ext = Qubit_Extremal_POVM_ParamSpace(Qalpha=100, Qphi=32, device=device)
Qb_QDP_ext = Quantum_DP(**kwargs, param_space=Asp_ext)
prob_succ_B_ext = Qb_QDP_ext.root.prob_success(q)


if not identical:
    print('System with {0} different qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Binary:\n    Best order  {0:.6f}\n    Worst order {1:.6f}'.format(
        *prob_succ_B))
    print('Binary_extremal:\n    Best order  {0:.6f}\n    Worst order {1:.6f}'.format(
        *prob_succ_B_ext))
else:
    print('System with {0} identical qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Binary   {0:.6f}'.format(*prob_succ_B))
    print('Binary_extremal   {0:.6f}'.format(*prob_succ_B_ext)) 
    
simulate(Qb_QDP, 1000, q);
simulate(Qb_QDP_ext, 1000, q);

System with 3 different qubits
Depolarizing parameter g = 0.3
Helstrom:
    Global 0.883115
    Local 0.877781
Binary:
    Best order  0.882135
    Worst order 0.879437
Binary_extremal:
    Best order  0.882135
    Worst order 0.879437


probability of success is 0.897


probability of success is 0.865


## Qutrit Projective: ternary vs binary

In [55]:
N, g, q, Qp = 3, 0.3, 1/2, 100
identical, use_CUDA = False, True
device, cache = 'cuda:0' if use_CUDA else 'cpu', not use_CUDA
rho_pos, rho_neg = generate_rhos(N, identical, g, dim=3, is_complex=False)

kwargs = {
    'N': N, 'rho_pos': rho_pos, 'rho_neg': rho_neg, 'interp_mode': 'linear',
    'Qp': Qp, 'device': device, 'cache': cache
}

prob_succ_H = helstrom(q, rho_pos, rho_neg)

Asp3 = Qutrit_Proj_ParamSpace(d=[2, 2, 2], Q=32, mode='ternary', device=device)
QQDP3 = Quantum_DP(**kwargs, param_space=Asp3)
prob_succ_T = QQDP3.root.prob_success(q)

Asp2 = Qutrit_Proj_ParamSpace(d=[2, 2, 2], Q=32, mode='binary', device=device)
QQDP2 = Quantum_DP(**kwargs, param_space=Asp2)
prob_succ_B = QQDP2.root.prob_success(q)

if not identical:
    print('System with {0} different qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Ternary:\n    Best order  {0:.6f}\n    Worst order {1:.6f}'.format(*prob_succ_T))
    print('Binary:\n    Best order  {0:.6f}\n    Worst order {1:.6f}'.format(*prob_succ_B))
else:
    print('System with {0} identical qubits'.format(N))
    print('Depolarizing parameter g = {0}'.format(g))
    print('Helstrom:\n    Global {0:.6f}\n    Local {1:.6f}'.format(*prob_succ_H))
    print('Ternary  {0:.6f}'.format(*prob_succ_T))
    print('Binary   {0:.6f}'.format(*prob_succ_B))
    
simulate(QQDP3, 1000, q);
simulate(QQDP2, 1000, q);

System with 3 different qubits
Depolarizing parameter g = 0.3
Helstrom:
    Global 0.909285
    Local 0.895788
Ternary:
    Best order  0.905928
    Worst order 0.904136
Binary:
    Best order  0.899667
    Worst order 0.898901


probability of success is 0.917


probability of success is 0.906


## Simulation Experiment over Parameter Grid

In [56]:
param_grid = [('N', [3, 4, 5, 6]), ('g', [0.05, 0.1, 0.3])]
num_trials = 110
em = ExperimentManager('test.pickle', param_grid, num_trials)

def simul_func(N, g):
    q, Qp = 1/2, 100
    identical, use_CUDA = True, True
    device, cache = 'cuda:0' if use_CUDA else 'cpu', not use_CUDA
    rho_pos, rho_neg = generate_rhos(N, identical, g, dim=2, is_complex=False)
    kwargs = {
        'N': N, 'rho_pos': rho_pos, 'rho_neg': rho_neg, 'interp_mode': 'linear',
        'Qp': Qp, 'device': device, 'cache': cache
    }
    prob_succ_H = helstrom(q, rho_pos, rho_neg)
    
    Asp = Qubit_Proj_ParamSpace(Qphi=16, device=device)
    Qb_QDP = Quantum_DP(**kwargs, param_space=Asp)
    prob_succ_B = Qb_QDP.root.prob_success(q)

    Asp_ext = Qubit_Extremal_POVM_ParamSpace(Qalpha=100, Qphi=32, device=device)
    Qb_QDP_ext = Quantum_DP(**kwargs, param_space=Asp_ext)
    prob_succ_B_ext = Qb_QDP_ext.root.prob_success(q)
    return np.concatenate([prob_succ_H, prob_succ_B, prob_succ_B_ext])

def callback(pbar, res):
    pbar.set_postfix(n=len(res), mean=np.round(np.mean(res, axis=0), 2))
    
em.run(simul_func, callback)

VBox()

In [57]:
hel_g, hel_l, qb, gb_ext = [em.export_xarray(lambda x: x[i]) for i in range(4)]
for x in [hel_g, hel_l, qb, gb_ext]:
    print(x.mean(axis=-1))

<xarray.DataArray (N: 4, g: 3)>
array([[0.872582, 0.833651, 0.787764],
       [0.868051, 0.890556, 0.802114],
       [0.915819, 0.905438, 0.848057],
       [0.919042, 0.900039, 0.854722]])
Coordinates:
  * N        (N) int64 3 4 5 6
  * g        (g) float64 0.05 0.1 0.3
<xarray.DataArray (N: 4, g: 3)>
array([[0.86092 , 0.822887, 0.784093],
       [0.835305, 0.861794, 0.784154],
       [0.900974, 0.891893, 0.843092],
       [0.892139, 0.876568, 0.838792]])
Coordinates:
  * N        (N) int64 3 4 5 6
  * g        (g) float64 0.05 0.1 0.3
<xarray.DataArray (N: 4, g: 3)>
array([[0.867064, 0.824937, 0.783775],
       [0.859225, 0.881642, 0.797745],
       [0.90685 , 0.89514 , 0.842789],
       [0.908431, 0.889596, 0.849018]])
Coordinates:
  * N        (N) int64 3 4 5 6
  * g        (g) float64 0.05 0.1 0.3
<xarray.DataArray (N: 4, g: 3)>
array([[0.867167, 0.825152, 0.783776],
       [0.859345, 0.881711, 0.797828],
       [0.906945, 0.89518 , 0.842792],
       [0.908513, 0.889634, 0.849056]]